const EXTENSION_LAYER_BASE = 2147483000

export const EXTENSION_LAYER = {
  badges: EXTENSION_LAYER_BASE + 10,
  widget: EXTENSION_LAYER_BASE + 20,
  reviewOverlay: EXTENSION_LAYER_BASE + 30,
  drawer: EXTENSION_LAYER_BASE + 40,
  panel: EXTENSION_LAYER_BASE + 50,
  modal: EXTENSION_LAYER_BASE + 60
} as const
