import type { UserProfile, Workspace } from "@/lib/collab-types";

export const defaultProfile: UserProfile = {
  id: "usr_1",
  name: "Mira Klein",
  email: "mira@acme.studio",
  title: "Product Designer",
  bio: "I coordinate design QA and triage across product launches.",
  avatarUrl: "",
  timezone: "UTC+2",
};

export const mockWorkspace: Workspace = {
  id: "ws_1",
  name: "Acme Studio",
  spaces: [
    {
      id: "ver_2026_04_29",
      name: "2026.04.29",
      notes: "Pre-release space for UI polish and pricing updates",
      createdAt: "2026-04-29T11:30:00.000Z",
    },
    {
      id: "ver_2026_04_18",
      name: "2026.04.18",
      notes: "Auth flows and dashboard updates space",
      createdAt: "2026-04-18T09:10:00.000Z",
    },
    {
      id: "ver_2026_04_01",
      name: "2026.04.01",
      notes: "Q2 launch landing page review",
      createdAt: "2026-04-01T08:00:00.000Z",
    },
    {
      id: "ver_2026_03_15",
      name: "2026.03.15",
      notes: "Onboarding flow redesign",
      createdAt: "2026-03-15T10:30:00.000Z",
    },
    {
      id: "ver_2026_03_01",
      name: "2026.03.01",
      notes: "Dark mode initial pass",
      createdAt: "2026-03-01T14:00:00.000Z",
    },
  ],
  tags: [
    { id: "tag_copy", label: "Copy", colorClass: "bg-mark-soft text-ink" },
    { id: "tag_ui", label: "UI", colorClass: "bg-paper-2 text-ink" },
    { id: "tag_a11y", label: "A11y", colorClass: "bg-paper-3 text-ink" },
    { id: "tag_bug", label: "Bug", colorClass: "bg-mark/20 text-ink" },
  ],
  members: [
    { id: "usr_1", name: "Mira Klein", initials: "MK", email: "mira@acme.studio", role: "owner" },
    { id: "usr_2", name: "Oscar Ruiz", initials: "OR", email: "oscar@acme.studio", role: "member" },
    { id: "usr_3", name: "Sara Green", initials: "SG", email: "sara@acme.studio", role: "member" },
  ],
  invites: [{ id: "inv_1", email: "alex@acme.studio", invitedBy: "Mira Klein", invitedAt: "2026-04-30T13:50:00.000Z" }],
  pins: [
    {
      id: "MRK-482",
      spaceId: "ver_2026_04_29",
      title: "Pricing card label missing",
      description:
        "The featured plan card needs a visible \"Most popular\" badge so users can scan pricing tiers quickly.",
      page: "/pricing",
      status: "open",
      tagIds: ["tag_copy", "tag_ui"],
      assigneeId: "usr_2",
      linearUrl: "https://linear.app/acme/issue/ACM-482",
      capture: {
        selector: ".pricing-card.featured > h3",
        viewport: "1440 × 900",
        browser: "Chrome 126",
        os: "macOS 15.4",
        screenshotUrl: "/window.svg",
        capturedAt: "2026-04-30T14:05:00.000Z",
      },
    },
    {
      id: "MRK-479",
      spaceId: "ver_2026_04_29",
      title: "Navbar contrast in dark mode",
      description:
        "Top navigation links become hard to read on dark surfaces. Needs a lighter token or explicit dark-mode override.",
      page: "/",
      status: "open",
      tagIds: ["tag_ui", "tag_a11y"],
      assigneeId: "usr_3",
      linearUrl: "https://linear.app/acme/issue/ACM-479",
      capture: {
        selector: "header nav a",
        viewport: "1280 × 720",
        browser: "Firefox 128",
        os: "Windows 11",
        capturedAt: "2026-05-01T09:20:00.000Z",
      },
    },
    {
      id: "MRK-475",
      spaceId: "ver_2026_04_29",
      title: "CTA button hover is too subtle",
      description: "Primary CTA hover state barely changes. Increase contrast shift so the button feels responsive.",
      page: "/",
      status: "closed",
      tagIds: ["tag_ui"],
      assigneeId: "usr_2",
      capture: { selector: ".hero-cta", viewport: "1440 × 900", browser: "Chrome 126", os: "macOS 15.4", capturedAt: "2026-04-29T16:10:00.000Z" },
    },
    {
      id: "MRK-469",
      spaceId: "ver_2026_04_18",
      title: "Form validation copy is unclear",
      description: "Error language should explain the exact correction needed instead of generic messages.",
      page: "/auth/sign-up",
      status: "closed",
      tagIds: ["tag_copy"],
      assigneeId: "usr_1",
      capture: { selector: ".form-error-message", viewport: "1440 × 900", browser: "Chrome 126", os: "macOS 15.4", capturedAt: "2026-04-18T11:40:00.000Z" },
    },
    {
      id: "MRK-467",
      spaceId: "ver_2026_04_18",
      title: "Password strength meter needs ARIA",
      description: "Screen readers cannot interpret the visual strength meter. Add aria-valuenow and role=meter.",
      page: "/auth/sign-up",
      status: "closed",
      tagIds: ["tag_a11y"],
      assigneeId: "usr_3",
      capture: { selector: ".password-meter", viewport: "1440 × 900", browser: "Chrome 126", os: "macOS 15.4", capturedAt: "2026-04-18T14:20:00.000Z" },
    },
    {
      id: "MRK-465",
      spaceId: "ver_2026_04_18",
      title: "Dashboard loading skeleton flickers",
      description: "The skeleton UI flashes for <100ms on fast connections. Add a delay threshold before showing it.",
      page: "/dashboard",
      status: "open",
      tagIds: ["tag_ui", "tag_bug"],
      assigneeId: "usr_2",
      capture: { selector: ".skeleton-container", viewport: "1280 × 720", browser: "Safari 18", os: "macOS 15.4", capturedAt: "2026-04-19T09:55:00.000Z" },
    },
    {
      id: "MRK-450",
      spaceId: "ver_2026_04_01",
      title: "Hero headline wraps awkwardly at 768px",
      description: "The main headline on the landing page creates a single orphan word on the second line at tablet width.",
      page: "/",
      status: "closed",
      tagIds: ["tag_ui"],
      assigneeId: "usr_1",
      capture: { selector: ".hero h1", viewport: "768 × 1024", browser: "Safari 18", os: "iPadOS 18", capturedAt: "2026-04-02T10:30:00.000Z" },
    },
    {
      id: "MRK-448",
      spaceId: "ver_2026_04_01",
      title: "Feature list bullet alignment off",
      description: "Custom bullet points in the feature section don't align with the text baseline on Firefox.",
      page: "/",
      status: "closed",
      tagIds: ["tag_ui", "tag_bug"],
      assigneeId: "usr_2",
      capture: { selector: ".feature-list li::before", viewport: "1440 × 900", browser: "Firefox 127", os: "Ubuntu 24.04", capturedAt: "2026-04-03T08:15:00.000Z" },
    },
    {
      id: "MRK-446",
      spaceId: "ver_2026_04_01",
      title: "Social proof section needs real numbers",
      description: "Placeholder stats (XXX teams, XXX marks) need to be replaced with actual counts before launch.",
      page: "/",
      status: "open",
      tagIds: ["tag_copy"],
      assigneeId: "usr_1",
      capture: { selector: ".social-proof", viewport: "1440 × 900", browser: "Chrome 125", os: "macOS 15.4", capturedAt: "2026-04-04T11:00:00.000Z" },
    },
    {
      id: "MRK-430",
      spaceId: "ver_2026_03_15",
      title: "Onboarding step 2 has dead click area",
      description: "The illustration in step 2 intercepts clicks but doesn't advance the flow. Needs pointer-events: none.",
      page: "/onboarding",
      status: "closed",
      tagIds: ["tag_bug"],
      assigneeId: "usr_3",
      capture: { selector: ".onboarding-step-2 .illustration", viewport: "1440 × 900", browser: "Chrome 125", os: "macOS 15.3", capturedAt: "2026-03-16T14:00:00.000Z" },
    },
    {
      id: "MRK-428",
      spaceId: "ver_2026_03_15",
      title: "Welcome copy feels generic",
      description: "The welcome headline says \"Welcome to Markly\" — should reference the user's workspace name for personalization.",
      page: "/onboarding",
      status: "closed",
      tagIds: ["tag_copy"],
      assigneeId: "usr_1",
      capture: { selector: ".welcome-heading", viewport: "1280 × 720", browser: "Chrome 125", os: "Windows 11", capturedAt: "2026-03-17T09:30:00.000Z" },
    },
    {
      id: "MRK-426",
      spaceId: "ver_2026_03_15",
      title: "Skip button is too hidden",
      description: "The skip-onboarding link is grey on grey at the bottom. Users miss it and feel trapped.",
      page: "/onboarding",
      status: "open",
      tagIds: ["tag_ui", "tag_a11y"],
      assigneeId: "usr_2",
      capture: { selector: ".skip-onboarding", viewport: "1440 × 900", browser: "Chrome 125", os: "macOS 15.3", capturedAt: "2026-03-18T10:45:00.000Z" },
    },
    {
      id: "MRK-410",
      spaceId: "ver_2026_03_01",
      title: "Dark mode toggle has no transition",
      description: "Theme switch is instant and jarring. Add a 200ms transition on background-color and color.",
      page: "/",
      status: "closed",
      tagIds: ["tag_ui"],
      assigneeId: "usr_2",
      capture: { selector: ".theme-toggle", viewport: "1440 × 900", browser: "Chrome 124", os: "macOS 15.3", capturedAt: "2026-03-02T11:15:00.000Z" },
    },
    {
      id: "MRK-408",
      spaceId: "ver_2026_03_01",
      title: "Card borders vanish in dark mode",
      description: "Border token uses a lightness that's identical to the dark card background. Needs a separate dark-mode border value.",
      page: "/dashboard",
      status: "closed",
      tagIds: ["tag_ui", "tag_bug"],
      assigneeId: "usr_3",
      capture: { selector: ".card", viewport: "1280 × 720", browser: "Firefox 126", os: "Windows 11", capturedAt: "2026-03-03T09:00:00.000Z" },
    },
    {
      id: "MRK-405",
      spaceId: "ver_2026_03_01",
      title: "Focus ring invisible on dark surfaces",
      description: "The brand-red focus ring doesn't contrast enough on dark backgrounds. Consider a lighter ring or double-ring technique.",
      page: "/dashboard",
      status: "closed",
      tagIds: ["tag_a11y"],
      assigneeId: "usr_1",
      capture: { selector: "button:focus-visible", viewport: "1440 × 900", browser: "Chrome 124", os: "macOS 15.3", capturedAt: "2026-03-04T15:30:00.000Z" },
    },
  ],
  comments: [
    { id: "c_1", pinId: "MRK-482", authorId: "usr_1", createdAt: "2026-04-30T14:12:00.000Z", type: "text", body: "Let's align this with the CTA hierarchy and keep it short." },
    { id: "c_2", pinId: "MRK-482", authorId: "usr_2", createdAt: "2026-04-30T15:02:00.000Z", type: "image", imageUrl: "/window.svg" },
    { id: "c_3", pinId: "MRK-479", authorId: "usr_3", createdAt: "2026-05-01T09:25:00.000Z", type: "text", body: "I can patch token contrast in this release branch." },
    { id: "c_4", pinId: "MRK-469", authorId: "usr_2", createdAt: "2026-04-18T12:30:00.000Z", type: "text", body: "Merged. Validation messages are now specific per field." },
    { id: "c_5", pinId: "MRK-450", authorId: "usr_1", createdAt: "2026-04-03T11:00:00.000Z", type: "text", body: "Fixed with a manual <br> and an orphan-safe CSS approach." },
    { id: "c_6", pinId: "MRK-430", authorId: "usr_3", createdAt: "2026-03-17T10:00:00.000Z", type: "text", body: "Added pointer-events: none to the SVG wrapper." },
    { id: "c_7", pinId: "MRK-410", authorId: "usr_2", createdAt: "2026-03-03T14:00:00.000Z", type: "text", body: "Transition added. Also fixed the flash-of-light-theme on load." },
  ],
};
